apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    aadpodidbinding: default
spec:
  containers:
    - name: test
      image: debian
      command: ["bash"]
      args:
        - -c
        - apt update; apt install -y git maven; git clone https://github.com/Azure-Samples/compute-java-manage-vm-from-vm-with-msi-credentials; cd compute-java-manage-vm-from-vm-with-msi-credentials; mvn clean compile exec:java -Dexec.args="%s %s %s"; tail -f /dev/nulls
  nodeSelector:
    kubernetes.io/os: linux